[package]
name = "rules_tokens"
version = "0.1.0"

[lib]
name = "rules_tokens"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
rules_erc1155 = { git = "https://github.com/ruleslabs/starknet-erc-1155.git" }
messages = { git = "https://github.com/ruleslabs/starknet-messages.git" }
rules_utils = { git = "https://github.com/ruleslabs/starknet-utils.git" }
starknet = ">=1.0.0"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true

# Enable CASM codegen.
casm = true
